language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head
  - ree
  # TODO: Uncomment when rbx will handle Thread termination correctly
  # - rbx-18mode
  # - rbx-19mode
  # TODO: Uncomment when popen3 will work correctly on JRuby
  # - jruby-18mode
  # - jruby-19mode
  # - jruby-head
